#!/bin/bash
# Fix: Vercel serverless function format

echo "🔧 Fixing Vercel serverless function format..."
echo ""
echo "✅ Changes made:"
echo "  - api/routes.js: Changed to default export handler"
echo "  - api/locations.js: Changed to default export handler"
echo "  - Added HTTP method routing (GET, POST, PUT, DELETE)"
echo "  - Fixed 'Invalid export' error"
echo ""
echo "📝 Next steps:"
echo "  1. git add -A"
echo "  2. git commit -m 'fix: use default export for Vercel serverless functions'"
echo "  3. git push origin main"
echo ""
echo "🚀 After pushing:"
echo "  - Vercel will auto-redeploy"
echo "  - Monitor deployment in Vercel Dashboard"
echo "  - Check Function Logs for errors"
echo ""
echo "💡 API URLs will work like:"
echo "  GET  /api/routes          (get all)"
echo "  GET  /api/routes?id=1     (get one with locations)"
echo "  POST /api/routes          (create)"
echo "  PUT  /api/routes?id=1     (update)"
echo "  DELETE /api/routes?id=1   (delete)"
echo ""
echo "  GET  /api/locations       (get all)"
echo "  GET  /api/locations?id=1  (get one)"
echo "  POST /api/locations       (create)"
echo "  POST /api/locations/1?imageUrl=... (add image)"
echo "  PUT  /api/locations?id=1  (update)"
echo "  DELETE /api/locations?id=1 (delete)"
echo "  DELETE /api/locations/1?imageUrl=... (delete image)"
